version: '3.3'

# NOTE: you may have to run 'xhost local:docker' before the
# docker container can access your host's X server

services:
  ortho:
    build: .
    volumes:
    - ${HOME}/.Xauthority:/ortho/.Xauthority:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:ro
    - .:/ortho/ortho:Z
    environment:
    - DISPLAY=${DISPLAY}
    restart: "no"

